@echo off
echo Creating virtual environment (if it doesn't exist)...
python -m venv venv
call venv\Scripts\activate

echo Installing requirements...
pip install -r requirements.txt

echo Setting up database...
python -m backend.db_access.database_initialiser

echo Starting backend...
python -m backend.app